server:
  port: 8083
spring:
  application:
    name: api-gateway
  zipkin:
    baseUrl: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch_registry: true
    register-with-eureka: true